# Generated by Django 5.1 on 2024-09-30 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Overseer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=20)),
                ('username', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=13)),
                ('priviliege', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Produks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=13)),
                ('description', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=13)),
                ('stok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.IntegerField(choices=[(1, 'Overseer'), (2, 'Member')])),
            ],
        ),
        migrations.CreateModel(
            name='HewanTernak',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=13)),
                ('description', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=13)),
                ('status', models.CharField(max_length=255)),
                ('tanggal_masuk', models.DateField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sia.members')),
            ],
        ),
    ]
