# Generated by Django 5.1 on 2024-10-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0002_alter_overseer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
