# Generated by Django 5.1 on 2024-10-16 04:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sia', '0003_alter_members_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hewanternak',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='hewan_ternak/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produks',
            name='image',
            field=models.ImageField(default=1, upload_to='produks/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hewanternak',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='overseer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='produks',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
